[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "gulp2p"
version = "0.1.0"
description = "For preprocessing data from two-photon imaging  of head-fixed flies walking in virtual reality"
authors = [
    {name = "DanTurner-Evans", email = "65718402+DanTurner-Evans@users.noreply.github.com"},
    {name = "AliShenasa", email = "38480296+AliShenasa@users.noreply.github.com"},
    ]
readme = "README.md"

dependencies = [
    "scanimage-tiff-reader",
    "numpy",
    "scikit-image ",
    "scipy",
    "napari",
    "opencv-python",
    "pandas",
    "matplotlib",
    "pingouin",
    "pyqt6",
    "shapely",
    "strictyaml",
    "pytest",
    ]
